### ISSUE TITLE
Add headers for Comic Vine sections

### ISSUE THREAD

**Issue by lcfhines** [malvinaH/marvel-for-dummies#37]
Add headers to each column in the Comic Vine section that match the Marvel section "Comics" and "Series" sections

- [x] column 1: something like "What the Marvel Universe fans are saying"
- [x] column 2: something like "Quick Facts"

![Image](https://user-images.githubusercontent.com/113798073/195740936-38d3dff2-15e2-478b-a8b5-9ca44bceb10b.png)

**Comment by malvinaH** [comment]
Closing the issue after deciding it was not necessary.
