### ISSUE TITLE
Display information on the character from Comic Vine

### ISSUE THREAD

**Issue by lcfhines** [malvinaH/marvel-for-dummies#4]
- [x] Create a container with proper id = vine-info
- [x] Create two columns with proper ids (id= vine-description , id = vine-facts)
- [x] In the vine-description column, add p element with id = vine-deck and display deck
- [x] In the vine-facts column, add ul element with id = vine-list
- [x] In vine-list, add li element with id = vine-real-name and display real name
- [x] In vine-list, add li element with id = vine-origin and display origin
- [x] In vine-list, add li element id = vine-issue-name and display name of first issue
- [x] In vine-list, add li element id = vine-issue-number and display number of first issue
- [ ] Adding the data from the API

**Comment by malvinaH** [comment]
Issue not necessary. It was decided to not display data from Comic Vine.
