### ISSUE TITLE
Display characters that I save as favorites even if I refresh the page

### ISSUE THREAD

**Issue by lcfhines** [malvinaH/marvel-for-dummies#9]
- [x] Create container for favorite characters with id = favorite-characters
- [x] For loop for each saved character:
- [x] Create card element for each saved character with id = character-card
- [x] Create header for each card with character's name  id = character-name
- [x] Create body for each card with thumbnail image of character id = character-thumbnail
- [x] Fetch and print thumbnail from Marvel API

**Comment by malvinaH** [comment]
Unshift method was used instead of for loop.
